# Generated by Django 5.0.6 on 2024-10-13 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_T_Toners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.CharField(max_length=50)),
                ('activo', models.CharField(max_length=30)),
                ('numero_impresoras', models.PositiveIntegerField()),
                ('referencia', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[('N/A', 'N/A'), ('HP', 'HP'), ('SAMSUNG', 'SAMSUNG'), ('KYOSERA', 'KYOSERA'), ('EPSON', 'EPSON')], default='N/A', max_length=7)),
                ('toner_de_impresora', models.CharField(choices=[('105A', '105A'), ('30A', '30A'), ('83A', '83A'), ('136A', '136A'), ('175A', '175A'), ('17A', '17A'), ('19A', '19A'), ('85A', '85A'), ('226A', '226A'), ('D1015', 'D1015'), ('TINTA', 'TINTA'), ('N/A', 'N/A')], default='N/A', max_length=5)),
                ('otro_toner', models.CharField(choices=[('105A', '105A'), ('30A', '30A'), ('83A', '83A'), ('136A', '136A'), ('175A', '175A'), ('17A', '17A'), ('19A', '19A'), ('85A', '85A'), ('226A', '226A'), ('D1015', 'D1015'), ('TINTA', 'TINTA'), ('N/A', 'N/A')], default='N/A', max_length=5)),
                ('cantidad_toner', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_T_Toners_Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.CharField(max_length=50)),
                ('activo', models.CharField(max_length=30)),
                ('numero_impresoras', models.PositiveIntegerField()),
                ('referencia', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[('N/A', 'N/A'), ('HP', 'HP'), ('SAMSUNG', 'SAMSUNG'), ('KYOSERA', 'KYOSERA'), ('EPSON', 'EPSON')], default='N/A', max_length=7)),
                ('toner_de_impresora', models.CharField(choices=[('105A', '105A'), ('30A', '30A'), ('83A', '83A'), ('136A', '136A'), ('175A', '175A'), ('17A', '17A'), ('19A', '19A'), ('85A', '85A'), ('226A', '226A'), ('D1015', 'D1015'), ('MLT-D1018', 'MLT-D1018'), ('101S', '101S'), ('TINTA', 'TINTA'), ('N/A', 'N/A')], default='N/A', max_length=9)),
                ('otro_toner', models.CharField(choices=[('105A', '105A'), ('30A', '30A'), ('83A', '83A'), ('136A', '136A'), ('175A', '175A'), ('17A', '17A'), ('19A', '19A'), ('85A', '85A'), ('226A', '226A'), ('D1015', 'D1015'), ('MLT-D1018', 'MLT-D1018'), ('101S', '101S'), ('TINTA', 'TINTA'), ('N/A', 'N/A')], default='N/A', max_length=9)),
                ('cantidad_toner', models.PositiveBigIntegerField()),
                ('comprobado', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('REGISTRAR', 'REGISTRAR')], default='SI', max_length=9)),
                ('zona', models.CharField(choices=[('SIN DEFINIR', 'SIN DEFINIR'), ('SUR', 'SUR'), ('NORTE', 'NORTE'), ('ALEDAÑOS', 'ALEDAÑOS')], default='SIN DEFINIR', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Tonner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.PositiveBigIntegerField()),
                ('Numero_Toner', models.CharField(max_length=20)),
                ('Estado', models.CharField(choices=[('Disponible', 'Disponible')], default='Disponible', max_length=10)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('firma', models.ImageField(upload_to='firmas/')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Datos.area')),
            ],
        ),
        migrations.CreateModel(
            name='Toner_M_Recargados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('ENTREGADO', 'ENTREGADO'), ('RECARGANDO', 'RECARGANDO')], default='RECARGANDO', max_length=10)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('fecha_recibido', models.DateTimeField(null=True)),
                ('toner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Datos.tonner')),
            ],
        ),
        migrations.CreateModel(
            name='Retiro_Tonner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.PositiveIntegerField(default=1)),
                ('cantidad_retirada', models.PositiveIntegerField(default=1)),
                ('caso_GLPI', models.CharField(default='En Espera', max_length=100)),
                ('descripcion', models.TextField(default='Sin descripción', max_length=500)),
                ('fecha_retiro', models.DateTimeField(auto_now_add=True)),
                ('r_persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Datos.persona')),
                ('r_tonner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Datos.tonner')),
            ],
        ),
        migrations.CreateModel(
            name='Recargar_Toner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_Recargar', models.PositiveIntegerField()),
                ('fecha_Recarga', models.DateTimeField(auto_now_add=True)),
                ('toner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Datos.tonner')),
            ],
        ),
    ]
